-- 회원 테이블 생성
CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    TELECOM VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(20) NOT NULL,
    NATIONALITY VARCHAR2(20) NOT NULL,
    PHONENUMBER VARCHAR2(20) NOT NULL,
    CERTNAME VARCHAR2(20) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);
--테이블 별칭 추가
COMMENT ON TABLE MEMBERS IS '회원';

--테이블의 컬럼값 별칭 추가
COMMENT ON COLUMN MEMBERS.MNO IS '회원 번호';
COMMENT ON COLUMN MEMBERS.ID IS '아이디';
COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.NAME IS '이름';
COMMENT ON COLUMN MEMBERS.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBERS.TELECOM IS '통신사';
COMMENT ON COLUMN MEMBERS.GENDER IS '성별';
COMMENT ON COLUMN MEMBERS.NATIONALITY IS '국적';
COMMENT ON COLUMN MEMBERS.PHONENUMBER IS '휴대폰 번호';
COMMENT ON COLUMN MEMBERS.CERTNAME IS '약관동의 여부';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '생성일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '변경일';

DESC MEMBERS;

SELECT * 
FROM MEMBERS;

-- 게시판글 테이블 생성
CREATE TABLE BOARD(
    BNO NUMBER NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(20) NOT NULL,
    USER_EMAIL VARCHAR2(20) NOT NULL,
    CONTENTS VARCHAR2(20) NOT NULL,
    MOD_PWD DATE NOT NULL,
    MNO VARCHAR2(20) NOT NULL
);


ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_BNO_PK PRIMARY KEY(BNO);

CREATE SEQUENCE MEMBERS_NO_SEQ
INCREMENT BY 1
START WITH 1;

