-- 회원 테이블 생성
CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(16) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    TELECOM VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(9) NOT NULL,
    NATIONALITY VARCHAR2(9) NOT NULL,
    PHONENUMBER VARCHAR2(13) NOT NULL,
    CERTNAME VARCHAR2(5) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);
--테이블 별칭 추가
COMMENT ON TABLE MEMBERS IS '회원';

--테이블의 컬럼값 별칭 추가
COMMENT ON COLUMN MEMBERS.MNO IS '회원 번호';
COMMENT ON COLUMN MEMBERS.ID IS '아이디';
COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.NAME IS '이름';
COMMENT ON COLUMN MEMBERS.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBERS.TELECOM IS '통신사';
COMMENT ON COLUMN MEMBERS.GENDER IS '성별';
COMMENT ON COLUMN MEMBERS.NATIONALITY IS '국적';
COMMENT ON COLUMN MEMBERS.PHONENUMBER IS '휴대폰 번호';
COMMENT ON COLUMN MEMBERS.CERTNAME IS '약관동의 여부';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '생성일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '변경일';

--제약조건 추가
ALTER TABLE MEMBERS
ADD CONSTRAINT TELECOM_CHECK CHECK(TELECOM 
IN ('SKT', 'KT', 'LG U+', 'SKT 알뜰폰', 'KT 알뜰폰',  'LG U+ 알뜰폰'));

ALTER TABLE MEMBERS
ADD CONSTRAINT GENDER_CHECK CHECK(GENDER
IN ('남성', '여성'));

ALTER TABLE MEMBERS
ADD CONSTRAINT NATIONALITY_CHECK CHECK(NATIONALITY
IN ('내국인', '외국인'));

ALTER TABLE MEMBERS
ADD CONSTRAINT CERTNAME_CHECK CHECK(CERTNAME
IN ('TRUE', 'FALSE'));

DESC MEMBERS;

SELECT * 
FROM MEMBERS;

-- 게시판글 테이블 생성
CREATE TABLE BOARD(
    BNO NUMBER NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(30) NOT NULL,
    CONTENTS VARCHAR2(4000) NOT NULL,
    MOD_PWD NUMBER(4,0) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL,
    MNO NUMBER NOT NULL
);

DESC BOARD;

COMMENT ON COLUMN BOARD.BNO IS '게시글 번호';
COMMENT ON COLUMN BOARD.USER_NAME IS '게시글 작성자 이름';
COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.USER_EMAIL IS '게시글 작성자 이메일';
COMMENT ON COLUMN BOARD.CONTENTS IS '게시글 내용';
COMMENT ON COLUMN BOARD.MOD_PWD IS '게시글 수정 비밀번호';
COMMENT ON COLUMN BOARD.CRE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.MOD_DATE IS '게시글 수정일';
COMMENT ON COLUMN BOARD.MNO IS '게시글 작성자 번호';


ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_BNO_PK PRIMARY KEY(BNO);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_MNO_FK foreign KEY(MNO) references MEMBERS(MNO);

--MEMBERS_NO 자동 추가 시퀸스 생성
CREATE SEQUENCE MEMBERS_NO_SEQ
INCREMENT BY 1
START WITH 1;

--구분하기 위해 BOARD_NO는 1000부터 시작
CREATE SEQUENCE BOARD_NO_SEQ
INCREMENT BY 1
START WITH 1000;


--멤버 추가 
INSERT INTO MEMBERS
VALUE(MNO, ID, PWD, EMAIL, NAME, BIRTHDAY, TELECOM
    , GENDER, NATIONALITY, PHONENUMBER, CERTNAME, CRE_DATE, MOD_DATE)
VALUES(MEMBERS_NO_SEQ.NEXTVAL, 'jihun', 'ji123', 'jihun@test.com', '박지훈'
    ,'1992-01-28', 'SKT 알뜰폰', '남성', '내국인', '010-4930-2078'
    , 'TRUE', SYSDATE, SYSDATE);
    
INSERT INTO MEMBERS
VALUE(MNO, ID, PWD, EMAIL, NAME, BIRTHDAY, TELECOM
    , GENDER, NATIONALITY, PHONENUMBER, CERTNAME, CRE_DATE, MOD_DATE)
VALUES(MEMBERS_NO_SEQ.NEXTVAL, 'hyunsoo', 'hyunsoo123', 'hyunsoo@test.com', '이현수'
    ,'1994-12-25', 'SKT', '남성', '내국인', '010-6345-1062'
    , 'TRUE', SYSDATE, SYSDATE);
    
INSERT INTO MEMBERS
VALUE(MNO, ID, PWD, EMAIL, NAME, BIRTHDAY, TELECOM
    , GENDER, NATIONALITY, PHONENUMBER, CERTNAME, CRE_DATE, MOD_DATE)
VALUES(MEMBERS_NO_SEQ.NEXTVAL, 'chanu', 'chanu123', 'chanu@test.com', '임찬우'
    ,'1996-12-21', 'KT', '남성', '내국인', '010-3206-3062'
    , 'TRUE', SYSDATE, SYSDATE);

SELECT MNO, ID, PWD, EMAIL, NAME 
FROM MEMBERS;

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '임찬우', '오늘 태풍', 'chanu@test.com'
, '오늘은 태풍 카눈이 올거 같은 느낌이다 근데 시원해서 기분이 좋다.', '1234', SYSDATE, SYSDATE, 3
);

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '박지훈', '네이버 입사', 'jihun@test.com'
, '네이버 회원가입 따오면 입사 할수 있다 근데 나는 지금 따옴 굳', '1234', SYSDATE, SYSDATE, 1
);

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '이현수', '커담은 진리', 'hyunsoo@test.com'
, '커피와 담배 조합 발견한 사람은 상 줘야된다 너네는 이런거 배우지 마라', '1234', SYSDATE, SYSDATE, 2
);

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '박지훈', '오늘은 2000년', 'jihun@test.com'
, '종말은 오지 않았다.', '1234', '2000-01-01', '2006-07-01', 1
);

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '이현수', '오 뭐 먹', 'hyunsoo@test.com'
, '제곧네', '1234', '2005-03-03', '2006-05-05', 2
);

INSERT INTO BOARD
VALUE(BNO, USER_NAME, TITLE, USER_EMAIL, CONTENTS, MOD_PWD, CRE_DATE, MOD_DATE, MNO)
VALUES(BOARD_NO_SEQ.NEXTVAL, '임찬우', '성지 순례', 'chanu@test.com'
, '성지 순례 왔습니다.', '1234', '2005-06-06', '2020-01-01', 3
);

SELECT *
FROM BOARD;